version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://nginx:8080 --no-chunked-encoding run tottori.yude.jp
    volumes:
      - '/data/.cloudflared:/root/.cloudflared'
