version: '3.8'
services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        user: root
        restart: always
        command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
