version: '3.7'

services:
  mirakc:
    image: yude-mirakc
    container_name: mirakc
    init: true
    restart: unless-stopped
    volumes:
      - mirakc-epg:/var/lib/mirakc/epg
      - ./config.yml:/etc/mirakc/config.yml:ro
    ports:
      - 40772:40772

volumes:
  mirakc-epg:
    name: mirakc_epg
    driver: local