services:
  nostr:
    container_name: nostr-relay
    image: ghcr.io/yude/nostr-rs-relay:master
    restart: always
    volumes:
      - type: bind
        source: "./data"
        target: "/usr/src/app/db"
      - type: bind
        source: "./config.toml"
        target: "/usr/src/app/config.toml"
        