version: '3.7'

services:
  epgstation:
    build:
        context: "./epgstation"
        dockerfile: "debian.Dockerfile"
    volumes:
        - ./epgstation/config:/app/config
        - ./epgstation/data:/app/data
        - ./epgstation/thumbnail:/app/thumbnail
        - ./epgstation/logs:/app/logs
        - ./recorded:/app/recorded
        - ./epgs-to-discord/config.toml:/root/.config/epgs-to-discord/config.toml
    environment:
        TZ: "Asia/Tokyo"
    ports:
        - "8888:8888"
        - "8889:8889"
    restart: always


volumes:
  mirakc-epg: