services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    image: ghcr.io/yude/youbine:master
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://app:3000 --no-chunked-encoding run youbine.yude.jp
    volumes:
      - '/home/ubuntu/.cloudflared:/root/.cloudflared'