version: '3.8'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    restart: always
    hostname: ldap.soine.site
    ports:
      - 636:636
      - 389:389
    env_file:
      - .env
    environment:
      LDAP_ORGANISATION: "soine.site"
      LDAP_DOMAIN: "soine.site"
      LDAP_READONLY_USER: "false"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
    volumes:
      - ./data/ldap_db:/var/lib/ldap
      - ./data/ldap_config:/etc/ldap/slapd.d
      - ./data/certs:/container/service/slapd/assets/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  lam:
    image: ldapaccountmanager/lam
    container_name: lam
    user: 0:0
    restart: always
    env_file:
      - .env
    environment:
      LDAP_DOMAIN: "soine.site"
      LDAP_BASE_DN: "dc=soine,dc=site"
      LDAP_USERS_DN: "ou=people,dc=soine,dc=site"
      LDAP_GROUPS_DN: "ou=groups,dc=soine,dc=site"
      LDAP_SERVER: "ldap://ldap:389"
      LAM_LANG: "ja_JP"
      VIRTUAL_HOST: "lam"
      CERT_NAME: "ldap"
    depends_on:
      - ldap
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - lam-config:/etc/ldap-account-manager
      - lam-lib:/var/lib/ldap-account-manager

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: on-failure:3
    environment:
      DEFAULT_HOST: "lam"
    ports:
      - 22002:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - ldap
      - lam
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudflared-soine-nginx:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://192.168.200.2 --no-chunked-encoding run soine.site
    volumes:
      - '/root/.cloudflared:/root/.cloudflared'

volumes:
  lam-config:
  lam-lib:
