version: '3.9'

services:
  # PaperMC
  paper:
    image: ghcr.io/yudejp/paper-docker:master
    restart: always
    container_name: papermc
    ports:
      - 25565:25565
    stdin_open: true
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx2G"
    volumes:
      - ./paper:/app
    depends_on:
      - "db"

  # MariaDB
  db:
    restart: unless-stopped
    image: mariadb:10.7.3-focal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/log:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
        TZ: 'Asia/Tokyo'
        MYSQL_ROOT_PASSWORD: 'root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://paper:8100 --no-chunked-encoding run bluemap.yude.jp
    volumes:
      - '/root/.cloudflared:/root/.cloudflared'

  cloudflared-game:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url tcp://paper:25565 --no-chunked-encoding run mc.yude.jp
    volumes:
      - '/root/.cloudflared:/root/.cloudflared'
